### ISSUE TITLE
Question: I'm trying to apply shadows to my card view but is not showing, have you any idea why?

### ISSUE THREAD

**Issue by sadiq81** [Yalantis/Koloda#411] opened 2019-01-17 12:10 UTC
# Report

> The more information you provide, the faster we can help you.

⚠️ Select what you want - **a feature request** or **report a bug**. Please remove the section you aren't interested in.

###  What do you want to add?

> Please describe what you want to add to the component. 

### How should it look like?

> Please add images. 

###  What did you do?

> Please replace this with what you did. 

### What did you expect to happen?

> Please replace this with what you expected to happen.  

### What happened instead?

> Please replace this with what happened instead.

### Your Environment

- Version of the component: _insert here_
- Swift version: _insert here_
- iOS version: _insert here_
- Device: _insert here_
- Xcode version: _insert here_
- If you use Cocoapods: _run `pod env | pbcopy` and insert here_ 
- If you use Carthage: _run `carthage version | pbcopy` and insert here_

### Project that demonstrates the bug

> Please add a link to a project we can download that reproduces the bug.

**Comment by den-zv** [comment] 2019-03-27 16:47
I've tried to add shadow to view that I'm returning in `KolodaViewDataSource`'s `func koloda(_ koloda: KolodaView, viewForCardAt index: Int) -> UIView` method and it worked.

Looks like the problem is in the way you're trying to add shadows (did you check your view's `clipsToBounds` property?).

Closing this issue.
Please ping us back with more information in case problem is still there.

**Closed by den-zv** 2019-03-27 16:47 UTC
