### ISSUE TITLE
Revert Action Crash

### ISSUE THREAD

**Issue by muhasturk** [Yalantis/Koloda#200] opened 2016-08-22 11:37 UTC
Application is still crashing when there is no card on front and tring to do revert action even the koloda checking the number of cards 

``` swift
    public func revertAction() {
        if currentCardIndex > 0 && !animating {
        }
}
```

Xcode gives me

`fatal error: Index out of range`

Any suggestion?

**Comment by serejahh** [comment] 2016-08-22 13:34
Hi @muhasturk! Thanks for reporting the issues.

Could you describe preconditions and steps to reproduce the bug?

**Comment by muhasturk** [comment] 2016-08-22 14:09
Ok, I have an array that holds the number of events that is gonna be shown by koloda view. When networking has started to download whole information from service layer, that array is an empty. Also we have a button that we use to revert action. 

In that time, revert button cause to crash an application because of the array is empty. However I did not understand why revert button causing to crash. 

** This is by button trigger to revertAction **
```swift
  @IBAction func undoEvent(sender: AnyObject) {
      self.kolodaView.revertAction()
  }
```

If the data source of koloda view is empty, revertAction method cause to crash application.

You already check the currentCardIndex but still crashing if the data source is empty.

** Temporary solution for me ** 
``` swift
    if numberOfKidofunlaEvents > 0 && kolodaView.currentCardIndex > 0 {
      self.kolodaView.revertAction()
    }
```

```
Apple Swift version 2.2 (swiftlang-703.0.18.8 clang-703.0.31)
Target: x86_64-apple-macosx10.9
Darwin mhPRO.local 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64 
Using Koloda (3.1.1)
```

**Comment by freaqed** [comment] 2017-05-11 15:18
Hi guys!
Issue seems to be fixed in the latest version. Please check it out and let me know if isn't work.

**Closed by freaqed** 2017-05-11 15:18 UTC
Labels: bug, help wanted
