### ISSUE TITLE
Trigger revertAction() in CustomView

### ISSUE THREAD

**Issue by sash83** [Yalantis/Koloda#130] opened 2016-03-11 12:00 UTC
I'm using a custom view that I load within the KolodaView instead of images as cards. Is there any way to put the revertAction() function in this custom view? The purpose is to go back to previous card inside the card, not outside. I delegate the action from the custom view to a viewcontroller. Actions work fine apart from the revertAction function. (KolodaView is nil)

**Comment by tomekh7** [comment] 2016-03-14 14:04
I think, that technically it is possible. Could you provide some code you use so we can check if something is wrong?

**Comment by sash83** [comment] 2016-03-14 15:32
That's the outlet action of a button to return to previous card. It's in the class that is responsible for the custom view as cards:

`@IBAction func goToPreviousTip(sender: AnyObject) {
          customTipDelegate = swipeController
                                     if (customTipDelegate != nil) {
            customTipDelegate?.previousButtonTapped()
        }
        else {
            print("You forgot to set your reference in customTipDelegate to contain an instance of SwipeTipViewController!")
        }     
    }`

The protocol:

`protocol CustomTipViewDelegate:class {
  func previousButtonTapped()
  }`

And the protocol function in the swipecontroller class:

`func previousButtonTapped() {
        print("Previous button tapped!")
        kolodaView.revertAction()     
    }`

**Comment by tomekh7** [comment] 2016-03-15 12:22
Your logic looks fine so the issue is somewhere else. I suppose that your `kolodaView` is nil. Are you sure you properly assign value to this property?

**Comment by sash83** [comment] 2016-03-15 12:23
Yes, kolodaView is nil...

**Comment by tomekh7** [comment] 2016-03-18 11:52
Are you sure you have assigned value to `kolodaView` property? You have `@IBOutlet` so probably you use xibs/storyboards, please double check if you have this outlet connected. When/where you invoke `reloadData()` on `kolodaView`?

**Comment by sash83** [comment] 2016-03-21 10:13
<img width="260" alt="kolodaview" src="https://cloud.githubusercontent.com/assets/714842/13915498/5ffe101a-ef55-11e5-8bd2-83848993a344.png">

My approach is pretty much the same as your networking-example. I fetch data from Parse backend, it's similar to your fetchPhotos() function. I invoke reloadData() at the same position as you do.

**Comment by AEugene** [comment] 2016-03-24 12:38
Hello @sash83 . Could you make a demo project?

**Comment by sash83** [comment] 2016-03-24 23:37
https://github.com/sash83/KolodaDemo

I used your networking-example in the demo above and placed a button on the photoView to get back to previous card.
No success!

**Comment by tomekh7** [comment] 2016-03-25 08:31
@sash83 read your code again and check where and how you assign `viewController` property of KolodaPhotoView. This way it cannot work. You should assign this property in 
`func koloda(koloda: KolodaView, viewForCardAtIndex index: UInt) -> UIView`

**Comment by sash83** [comment] 2016-03-25 14:25
Can you please help me? How would you accomplish it?

I've updated my demo with a different way:

in `func koloda(koloda: KolodaView, viewForCardAtIndex index: UInt) -> UIView`:

` photoView?.previousButton.addTarget(self, action: "previousButton:", forControlEvents: .TouchUpInside)`

**Comment by AEugene** [comment] 2016-06-30 05:49
Hi @sash83 . You’ve created new instance of ViewController inside your card and it wasn’t loaded from xib, that's why KolodaView outlet was `nil`. If you want to use your approach you just have to set instance of current ViewController as delegate of your custom card in `viewForCardAtIndex`. Or you can simply do something like this:
<img width="957" alt="d25a4c0350e62eb230b36a29ac65b242" src="https://cloud.githubusercontent.com/assets/8107146/16478009/763f2262-3e9f-11e6-9553-f1ed8aa50e84.png">

**Closed by AEugene** 2016-06-30 05:49 UTC
