### ISSUE TITLE
Animation is not working if I tap on button 

### ISSUE THREAD

**Issue by garora12** [Yalantis/Koloda#348] opened 2018-01-12 13:16 UTC
# Report

        kolodaView?.swipe(.right)
I have used my custom view(full screen) which have some sub views and a collection view inside it.

Functionally it is working but without animation.

- Version of the component: Latest
- Swift version: 4
- iOS version: 11.2
- Device: Any iOS Device
- Xcode version: 9.2

**Comment by freaqed** [comment] 2018-01-18 11:05
Hello, @garora12!
Could you share some code?
I don't think it's problem with Koloda, since example app works just fine. Probably under some conditions, or external reasons it doesn't work in your case

**Comment by freaqed** [comment] 2018-03-19 10:59
Hi, @garora12 
I still not able to reproduce your issue so closing it.
If you still facing that problem please let us know

**Closed by freaqed** 2018-03-19 10:59 UTC
Labels: priority: low, status: need feedback, type: bug
