### ISSUE TITLE
How to use it in Swift3

### ISSUE THREAD

**Issue by helloworlderly** [Yalantis/Koloda#236] opened 2016-11-21 07:38 UTC
# Report

> The more information you provide, the faster we can help you.

⚠️ Select what you want - **a feature request** or **report a bug**. Please remove the section you aren't interested in.

###  What do you want to add?

> Please describe what you want to add to the component. 

### How should it look like?

> Please add images. 

###  What did you do?

> Please replace this with what you did. 

### What did you expect to happen?

> Please replace this with what you expected to happen.  

### What happened instead?

> Please replace this with what happened instead.

### Your Environment

- [ ] Version of the component: _insert here_
- [ ] Swift version: _insert here_
- [ ] iOS version: _insert here_
- [ ] Device: _insert here_
- [ ] Xcode version: _insert here_
- [ ] If you use Cocoapods: _run `pod env | pbcopy` and insert here_ 
- [ ] If you use Carthage: _run `carthage version | pbcopy` and insert here_

### Project that demonstrates the bug

> Please add a link to a project we can download that reproduces the bug.

**Comment by moger777** [comment] 2016-11-22 19:57
There is a swift-3 branch

**Comment by yhu98** [comment] 2016-12-05 06:10
What's holding back from merging swift-3 to the master?

**Comment by serejahh** [comment] 2016-12-11 08:31
Duplicate of #230

**Closed by serejahh** 2016-12-11 08:31 UTC
