### ISSUE TITLE
First card wrong frame with tab bar and Koloda 3.1.1

### ISSUE THREAD

**Issue by Faisal-AlNeela** [Yalantis/Koloda#156] opened 2016-05-26 15:53 UTC
I have an issue with the first card size when i change the tab and its still loading and when i get back to the tab the frame of the first card is small and some times its very small or its never appear so i should relaunch the app to make it work again!!!

**Comment by numen31337** [comment] 2016-05-26 19:58
Looks like an issue I mentioned here https://github.com/Yalantis/Koloda/issues/147

**Comment by Faisal-AlNeela** [comment] 2016-05-26 20:06
yes I think the same issue
do you have any information how to avoid it or why this is happening??

**Comment by Faisal-AlNeela** [comment] 2016-05-27 14:59
@numen31337  I have temporarily avoided this issue by creating a bool value and use it in ViewWillAppear() and "ViewWillDisAppear()"
and use this kooloda method  func kolodaShouldApplyAppearAnimation(koloda: KolodaView) -> Bool 
so that if the view have been disappeared we don't want to load koloda view with animation

**Comment by numen31337** [comment] 2016-05-27 15:19
@Faisal-AlNeela The weird thing about it is that I have such issue even having animation disabled at all. The only this that helped to make it visible again is:
kolodaView.alpha = 0.0
kolodaView.alpha = 1.0
I don't even know why this works

**Comment by Faisal-AlNeela** [comment] 2016-05-31 14:20
@numen31337  I can confirm that i didn't get this issue since i used my solution above, I hope you try it.
I didn't use the Alpha solution because when I add it in view appear its make koloda view like flash effect because of the change of alpha..

**Comment by AEugene** [comment] 2016-05-31 15:05
hi @Faisal-AlNeela @numen31337 I'll debug this issue.

**Comment by AEugene** [comment] 2016-06-30 05:57
Duplicate of #147

**Closed by AEugene** 2016-06-30 05:57 UTC

**Comment by xiaosongshu** [comment] 2017-01-07 07:40
@Faisal-AlNeela I'm still getting this issue with Koloda 4.0. Can you clarify what your solution was?

**Comment by tenaz3** [comment] 2017-05-13 13:54
I have the same issue on Koloda 4
