### ISSUE TITLE
Limit swipe animation to horizontal path?

### ISSUE THREAD

**Issue by nilshott** [Yalantis/Koloda#184] opened 2016-08-01 16:56 UTC
Is there a way to limit the swipe animation to a horizontal path without any rotation?

**Comment by AEugene** [comment] 2016-08-05 11:50
Hi @nilshott . We will add this functionality in future versions.

**Comment by AEugene** [comment] 2016-08-05 12:05
Duplicate of #163

**Closed by AEugene** 2016-08-05 12:05 UTC
Labels: duplicate, enhancement
