### ISSUE TITLE
Ability to change current card index

### ISSUE THREAD

**Issue by felix-dumit** [Yalantis/Koloda#143] opened 2016-04-28 21:18 UTC
Users should be able to change the index of the current card being shown.

Something like this, but that would take into account the current visible indexes to avoid unnecessary reloading,
```swift
   public func changeCurrentCardIndex(to index:Int) {
       clear()
       currentCardIndex = index
       reloadData()
   }
```

**Comment by numen31337** [comment] 2016-05-10 12:34
I was using a similar solution and it works

**Comment by AEugene** [comment] 2016-06-30 05:57
Duplicate of #33 .

**Closed by AEugene** 2016-06-30 05:57 UTC
Labels: duplicate

**Comment by felix-dumit** [comment] 2016-06-30 06:30
@AEugene Maybe there was a typo, I don't see how this a duplicate of #33 ?

**Comment by AEugene** [comment] 2016-06-30 06:34
@felix-dumit Sorry for misunderstanding, I've updated my comment.
